version: '3.1'
services:
  casnode:
    build:
      context: ./
      dockerfile: go-dockerfile
    ports:
     - 7000:7000
    depends_on:
     - db
  db:
    restart: always
    image: mysql:8.0.25
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - /usr/local/docker/mysqls:/var/lib/mysql



